<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-FFmpeg.Worker-1e99b3f9-8bde-491b-b3f5-b7e8a71f19a4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.5.1" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="MassTransit" Version="8.3.7" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.3.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuizzArena.Workers.Contracts\QuizzArena.Workers.Contracts.csproj" />
  </ItemGroup>
</Project>
